### ISSUE TITLE
Error on startup regarding conf loading

### ISSUE THREAD

**Issue by jwinterm** [jaycarey/ethtrader-ticker#1]
I am getting this error when I launch with start.sh:
`Unexpected error while running ticker.com.typesafe.config.ConfigException$BugOrBroken: Cannot load config from URL: https://github.com/jaycarey/ethtrader-ticker-conf/blob/master/ticker.conf` 

whether I use the original repo conf or my forked one. I am using open-jre at the moment, do you think it could be related to that?  

Edit: Just tried on home PC with Oracle JRE 8 and getting the same error, so don't think it's related to that.

**Comment by jaycarey** [comment]
Hey there, good to see someone else using the ticker code :)

You need to use the URL for the raw files, something like this:
https://raw.githubusercontent.com/jaycarey/ethtrader-ticker-conf/master/
Hope that helps!

**Comment by jwinterm** [comment]
That fixed it. I made a pull request if to change the example to that format if you want to merge it. Now I'm getting a 401 unauthorized error when connecting to reddit, but if I can't figure that out I'll ping you on reddit. Thanks!

**Comment by jaycarey** [comment]
Cool, will merge the PR. Make sure you add the bot account as a 'config' mod in order to update the CSS.
